// <auto-generated />
using CodeFirstPasos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstPasos.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20190718173048_CodeFirstPasos.Contexto2")]
    partial class CodeFirstPasosContexto2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirstPasos.Hormiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apodo");

                    b.Property<int>("Edad");

                    b.Property<string>("JuegoFavorito");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Hormigas");
                });
#pragma warning restore 612, 618
        }
    }
}
