
INSERT INTO WarehouseMovementTypes VALUES(GETUTCDATE(),NEWID(),'ENTRY',0)
INSERT INTO WarehouseMovementTypes VALUES(GETUTCDATE(),NEWID(),'DEPARTURE',1)
INSERT INTO WarehouseMovementTypes VALUES(GETUTCDATE(),NEWID(),'TRANSFER',1)
INSERT INTO WarehouseMovementTypes VALUES(GETUTCDATE(),NEWID(),'RETURN',0)
GO

