namespace Group.Salto.Common.Enums
{
    public enum WorkOrderColumnsEnum : int
    {
        Id = 0,
        InternalIdentifier = 1,
        ExternalIdentifier = 2,
        CreationDate = 3,
        AssignmentTime = 4,
        PickUpTime = 5,
        FinalClientClosingTime = 6,
        InternalClosingTime = 7,
        WorkOrderStatusId = 8,
        TextRepair = 9,
        Observations = 10,
        InsertedBy = 11,
        WorkOrderType = 12,
        Project = 13,
        SaltoClient = 14,
        EndClient = 15,
        ResolutionDateSla = 16,
        Phone = 17,
        Area = 18,
        Zone = 19,
        Subzona = 20,
        SiteName = 21,
        SitePhone = 22,
        Address = 23,
        ClosingCode = 24,
        ActionDate = 25,
        ResponsiblePersonName = 26,
        Queue = 27,
        City = 28,
        Province = 29,
        Manufacturer = 30,
        WorkOrderCategory = 31,
        ParentWOId = 33,
        ActuationEndDate = 34,
        NumWOsInSite = 35,
        NumSubWOs = 36,
        SiteCode = 37,
        AssetSerialNumber = 38,
        AssetNumber = 39,
        Maintenance = 40,
        StandardWarranty = 41,
        ManufacturerWarranty = 42,
        ExternalWorOrderStatus = 43,
        TotalWorkedTime = 44,
        OnSiteTime = 45,
        TravelTime = 46,
        Kilometers = 47,
        NumberOfVisitsToClient = 48,
        NumberOfIntervention = 49,
        MeetResolutionSLA = 50,
        MeetResponseSLA = 51,
        ClosingWODate = 52,
        SelectCheckbox = 100
    }
}