// <auto-generated />
using System;
using Aeropuerto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aeropuerto.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20190724102822_Aeropuerto.vuelo")]
    partial class Aeropuertovuelo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aeropuerto.Avion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Autonomia");

                    b.Property<string>("Modelo")
                        .HasColumnName("Modelo")
                        .HasMaxLength(150)
                        .IsUnicode(true);

                    b.Property<string>("Nombre")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Aviones");
                });

            modelBuilder.Entity("Aeropuerto.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria")
                        .HasColumnName("Categoria")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<string>("Nombre")
                        .HasMaxLength(200);

                    b.Property<decimal?>("Sueldo");

                    b.HasKey("Id");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("Aeropuerto.Vuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("IdAvion");

                    b.Property<int>("IdPiloto");

                    b.HasKey("Id");

                    b.HasIndex("IdAvion");

                    b.HasIndex("IdPiloto");

                    b.ToTable("Vuelo");
                });

            modelBuilder.Entity("Aeropuerto.Vuelo", b =>
                {
                    b.HasOne("Aeropuerto.Avion", "Avion")
                        .WithMany()
                        .HasForeignKey("IdAvion")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Aeropuerto.Piloto", "Piloto")
                        .WithMany("Vuelos")
                        .HasForeignKey("IdPiloto")
                        .HasConstraintName("ForeignKey_Vuelo_Avion")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
